//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCustomerTodoList.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public System.DateTime DateofBirth { get; set; }

        
    }
}
