//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCustomerTodoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODOList
    {
        public int TdlistID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<bool> Resolved { get; set; }
        public int CustomerID { get; set; }
    }
}
